iteration: 1.0
forecast_scenario: core
export_folder: E:\NorMITs Demand\test
assignment_model: NoRMS

# Input paths
matrices_to_grow_dir: T:\edge_training\files_needed\matrices
irsj_props_dir: T:\edge_training\files_needed\irsj_props

# Custom inputs files
demand_segments: U:\00_Inputs\GATInputs\demand_segments.csv
norms_to_edge_stns_path: I:\NorMITs Demand\import\edge_replicant\apply_growth\TLCs_EDGE.csv
ticket_type_splits: 
  edge_flows_path: U:\00_Inputs\GATInputs\FC_fullfat1819_NEW_DDG.csv
  splits_path: T:\edge_training\files_needed\ticket_splits
  flow_cat_path: U:\00_Inputs\GATInputs\FlowCats.csv

cube_exe: C:\Program Files\Citilabs\CubeVoyager\VOYAGER.EXE

# EDGE outputs
edge_growth_dir: I:\NorMITs Demand\import\edge_replicant\edge_inputs\output_data\Outputs\Apr 23 High

# Forecast years dictionary
# forecast year: EDGE growth factors file
forecast_years:
  2028: Out_Apr 23 High_2028_rate.csv.bz2