iteration: 1.2
forecast_scenario: Central
export_folder: E:\NorMITs Demand\test
assignment_model: NoRMS

# Input paths
matrices_to_grow_dir: T:\edge_training\files_needed\matrices
irsj_props_dir: T:\edge_training\files_needed\irsj_props

# Custom inputs files
demand_segments: U:\00_Inputs\GATInputs\demand_segments.csv
norms_to_edge_stns_path: U:\00_Inputs\GATInputs\TLCs_MOIRA.csv
ticket_type_splits:
  edge_flows_path: U:\00_Inputs\GATInputs\FC_fullfat1819_NEW_DDG.csv
  splits_path: T:\edge_training\files_needed\ticket_splits
  flow_cat_path: U:\00_Inputs\GATInputs\FlowCats.csv
  info: info

cube_exe: C:\Program Files\Citilabs\CubeVoyager\VOYAGER.EXE

# EDGE outputs
edge_growth_dir: I:\NorMITs Demand\import\edge_replicant\edge_inputs\output_data\Outputs\Jan 24 Central - Growth

# Forecast years dictionary
# forecast year: EDGE growth factors file
forecast_years:
  2023: Out_Jan 24 Central - Growth_2023_rate.csv.bz2

