raw_dlog_landuse:
  population: C:\Users\UKKXF022\Documents\Midlands_connect_freight\freight_and_economy_outputs\pop_constrained_totals_miham_test.csv
  employment: C:\Users\UKKXF022\Documents\Midlands_connect_freight\freight_and_economy_outputs\job_constrained_totals_miham_test.csv
notem_import_home: I:\NorMITs Demand\import\NoTEM
base_year: 2018
years:
  - 2050
# Iteration and location of the base TfN land use, which was used in D-Lit
land_use_import_home: I:\
land_use_iteration:
  base: iter3e
  future: iter3e
import_version:
  hb_production: 3.0
  hb_attraction: 2.3
  nhb_production: 3.0
trip_end_iteration: 1.0
export_folder: C:/Users/UKKXF022/Documents/Midlands_connect_freight/NorMits_Outputs
scenario: DLOG
overwrite_intermediary_landuse: true
